# Generated by Django 4.2.3 on 2023-07-26 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_alter_conversation_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
