# Generated by Django 4.2.3 on 2023-07-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userprofile_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='active',
        ),
    ]
